### ISSUE TITLE
Error in zigbee api ( reporting command)

### ISSUE THREAD

**Issue by han-alink** [tlaukkan/zigbee4java#109]
MinReporting interval is set twice (instead of MIN and MAX

        record.setMinimumReportingInterval(minInterval);
        record.setMinimumReportingInterval(maxInterval);
        record.setReportableChange(reportableChange);

**Comment by tlaukkan** [comment]
Thank you Han for the bug reports. I try to look at this during the weekend. If you have pull requests those would be much appreciated. I have some other pull requests in queue to check as well.

**Comment by han-alink** [comment]
Hi Tommy,

Glad to hear that you are still actively working on the zigbee4java project.

I’m not familiar with “pull requests”. I imported zigbee4java in Eclipse and are using the software in combination with HomeRun (my home control program). I’m not yet finished with it yet, but can control my Zigbee devices already and get reports from the sensor devices. I added the “LevelContrallableOutput device” (deviceId = 3). I think you should rename the device with deviceId = 1 to LevelControlSwitch 

I attached a patch file. This also contains some debugging statements which you should ignore. Have a close look and be warned: I’m not an expirienced java programmer!

Thanks for your effort,

Bset regards,

Han

 

Van: Tommi S.E. Laukkanen [mailto:notifications@github.com] 
Verzonden: dinsdag 29 november 2016 20:10
Aan: tlaukkan/zigbee4java
CC: han-alink; Author
Onderwerp: Re: [tlaukkan/zigbee4java] Error in zigbee api ( reporting command) (#109)

 

Thank you Han for the bug reports. I try to look at this during the weekend. If you have pull requests those would be much appreciated. I have some other pull requests in queue to check as well.
