### ISSUE TITLE
Please join discussion group

### ISSUE THREAD

**Issue by tlaukkan** [tlaukkan/zigbee4java#15]
@chris-hatton @cdjackson @presslab-us 

The URL to the FAQ: https://groups.google.com/d/forum/zigbee4java

**Comment by chris-hatton** [comment]
Joined.  FYI I’m slowly working on full Gradle support for zigbee4java (with equivalent to Maven profiles for Desktop/Android). With Gradle becoming the de-facto build system for Android, this will make zigbee4java useful to a wider audience.  I am new to Gradle so it’s taking a bit of time to get right (Maven seems a lot more straightforward at the moment…).

Thanks,
Chris

**Comment by tlaukkan** [comment]
Hi

Nice work Chris. There are lots of people and project appreciating gradle
support in server / desktop projects as well.

Cheers,
Tommi

2015-03-07 12:06 GMT+02:00 Chris Hatton <notifications@github.com>:

> Joined. FYI I’m slowly working on full Gradle support for zigbee4java
> (with equivalent to Maven profiles for Desktop/Android). With Gradle
> becoming the de-facto build system for Android, this will make zigbee4java
> useful to a wider audience. I am new to Gradle so it’s taking a bit of time
> to get right (Maven seems a lot more straightforward at the moment…).
>
> Thanks,
> Chris
>
> > On 7 Mar 2015, at 20:57, Tommi S.E. Laukkanen <notifications@github.com>
> wrote:
> >
> > @chris-hatton <https://github.com/chris-hatton> @cdjackson <
> https://github.com/cdjackson> @presslab-us <https://github.com/presslab-us
> >
> > The URL to the FAQ: https://groups.google.com/d/forum/zigbee4java <
> https://groups.google.com/d/forum/zigbee4java>
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/tlaukkan/zigbee4java/issues/15>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tlaukkan/zigbee4java/issues/15#issuecomment-77682427>.
>



-- 
Best regards,
Tommi Laukkanen

**Comment by tlaukkan** [comment]
By the way there is 2015 release thread at the google group. Contributors please check it out :).
