### ISSUE TITLE
Bug in ZigBeeEndpointImpl

### ISSUE THREAD

**Issue by alcastelo** [tlaukkan/zigbee4java#18]
Hi there.
A couple of days ago, I started to play with this great project and a netvox zigbee device.
I found what seems to be a little bug in the bindTo method of the ZigBeeEndpointImpl class.
When you are building the ZDO_BIND_REQ packet, the last parameter is declared as BindDstEP , but you are sending is endpoint.getDeviceTypeId().  
I think this is a  bug, as it should be sending endpoint.getEndPointAddress().
I will try to send a patch for your consideration.
Thanks you very much for your time and work.
Regards!!!!

**Comment by tlaukkan** [comment]
@alcastelo this looks like a valid fix. Would you like to make a pull request?

**Comment by alcastelo** [comment]
Thanks a lot.
I´m making a pull request right now!!!

**Comment by tlaukkan** [comment]
Thank you :+1:

**Comment by alcastelo** [comment]
Thanks to you for your work!! :+1:
