### ISSUE TITLE
Return error 25

### ISSUE THREAD

**Issue by cdjackson** [tlaukkan/zigbee4java#34]
Any idea what error 25 is -:

```log
20:25:31 206  DEBUG  <--!!!= 0xfe 0x03 0x44 0x80 0x19 0x01 0x1e 0xc1
20:25:31 206  WARN   Unknown status value: 25
```

I added the DEBUG printout here... Error 25 isn't in the manual :(

**Comment by tlaukkan** [comment]
This could be due to mixed up serial communications i.e. packet reading has not started from the beginning of the packet.
