### ISSUE TITLE
Javadoc online

### ISSUE THREAD

**Issue by cdjackson** [tlaukkan/zigbee4java#46]
I've created a javadoc for the API - it's available [here](http://tlaukkan.github.io/zigbee4java/)

**Comment by cdjackson** [comment]
Just to add - it would be great if we can improve the documentation in the project. Some of the classes are very limited (especially those derived from java4osgi)

:)

**Comment by tlaukkan** [comment]
This become out dated. Javadoc is available from maven repository.
