### ISSUE TITLE
Reporter interface doesn't fully describe attribute

### ISSUE THREAD

**Issue by cdjackson** [tlaukkan/zigbee4java#5]
The callback from the reporter interface only provides the attribute information - not the device or cluster. This means that it's difficult to set up a single reporter callback method to receive information from different clusters (or devices).

Have I missed something here? To me it seems preferable to have the additional information available in the reporter callback so the client doesn't have to (somehow) manage this itself (with multiple callbacks I guess).

**Comment by tlaukkan** [comment]
We add device and cluster identifiers to the callback method?

**Comment by cdjackson** [comment]
Yes - I think this would be a useful addition if you’re happy with that?  Do you want to do that change, or shall I have a look?

**Comment by tlaukkan** [comment]
Who ever gets at it first :). Let me know if you start by commenting in this thread and I will do the same. I might have a time slot in couple of hours to do some work with this issue.

**Comment by tlaukkan** [comment]
Doing some work on it now.

**Comment by cdjackson** [comment]
Thanks :)
