### ISSUE TITLE
Endpoint ID is a byte (signed!)

### ISSUE THREAD

**Issue by cdjackson** [tlaukkan/zigbee4java#6]
Endpoint in org.bubblecloud.zigbee.network.impl.ZigBeeEndpointImpl is defined as a byte. My Hue bulb reports two endpoints (which I'm yet to work out) - one is currently showing as -14, which presumably should show 242?
I'll likely change this to short - just logging it here so I don't forget.

**Comment by tlaukkan** [comment]
Nice work chris :)
