### ISSUE TITLE
Some clusters incorrectly categorized

### ISSUE THREAD

**Issue by cdealti** [tlaukkan/zigbee4java#71]
```org.bubblecloud.zigbee.api.cluster.general``` contains clusters that belong to other ctegories, for example the ```IlluminanceLevelSensing``` cluster belongs to the ```Measurement and Sensing``` category.
A refactor is going to break the current API (see also #70)

**Comment by tlaukkan** [comment]
I think we could refactor these clusters to proper locations now?

**Comment by tlaukkan** [comment]
Simple ZigBee API implements new ZCL structure which has been code generated fro specification and fixes this problem. The old API how ever remains the same and will not be changed to avoid breaking the compatibility.
