### ISSUE TITLE
sendSynchrouns(hwDriver, request, RESEND_TIMEOUT) = null  in windows 10 

### ISSUE THREAD

**Issue by SamLuky** [tlaukkan/zigbee4java#75]
Hello :) 

i  tried to run zig4java console with eclipse in windows 10 but the application crash even if all the other configurations are well ( dongle, firmware, args ). 

the crash occur when the step of creation of zigbee network is begin ! the reason is : sendSynchrouns(hwDriver, request, RESEND_TIMEOUT) = null  

whereas when i  run the same program in eclipse using a ubuttu machines the program run well and the console of the application is running .  the value of sendSynchrouns(hwDriver, request, RESEND_TIMEOUT) in this case is : 

sendSynchrouns(hwDriver, request, RESEND_TIMEOUT) = ZB_WRITE_CONFIGURATION_RSP{Status=SUCCESS(0)} 

hope that helps someone :)

**Comment by cdealti** [comment]
Can you set the log level in ```./zigbee-api/src/main/resources/log4j.xml``` to ```trace``` and provide a log?

**Comment by SamLuky** [comment]
hello ! i find that the problem was in the system Windows 10 ! i put the same program in Ubuntu and it's run well :)

**Comment by cdealti** [comment]
It should work on windows 10 too. However there have been reported other issues on Windows 10 (see #74).

**Comment by tlaukkan** [comment]
Hi Sam, do you still experience this problem? I am running without problems in windows 10 at the moment.
